In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/weather-prediction/seattle-weather.csv

In [2]:
df=pd.read_csv("/kaggle/input/weather-prediction/seattle-weather.csv")

In [3]:
df.sample(5)

            date  precipitation  temp_max  temp_min  wind  weather
128   2012-05-08            0.0      18.3       9.4   3.0      sun
1167  2015-03-13            2.0      17.2       7.8   2.2     rain
270   2012-09-27            0.0      22.8      10.0   1.7  drizzle
40    2012-02-10            2.5      12.8       6.7   3.0     rain
1279  2015-07-03            0.0      33.3      17.8   2.6      sun

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, accuracy_score

In [5]:
x = df[["precipitation", "temp_max", "temp_min", "wind"]]
y = df["weather"]
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [7]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

rf.fit(x_train, y_train)

y_pred_rf = rf.predict(x_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf, target_names=le.classes_))

Random Forest Accuracy: 0.8156996587030717
              precision    recall  f1-score   support

     drizzle       0.14      0.09      0.11        11
         fog       0.21      0.15      0.18        20
        rain       0.97      0.91      0.94       129
        snow       1.00      0.60      0.75         5
         sun       0.78      0.89      0.83       128

    accuracy                           0.82       293
   macro avg       0.62      0.53      0.56       293
weighted avg       0.80      0.82      0.81       293

In [8]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    random_state=42
)

gb.fit(x_train, y_train)

y_pred_gb = gb.predict(x_test)

print("Gradient Boosting Accuracy:", accuracy_score(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb, target_names=le.classes_))

Gradient Boosting Accuracy: 0.8327645051194539
              precision    recall  f1-score   support

     drizzle       0.17      0.09      0.12        11
         fog       0.29      0.10      0.15        20
        rain       0.98      0.91      0.94       129
        snow       0.75      0.60      0.67         5
         sun       0.77      0.95      0.85       128

    accuracy                           0.83       293
   macro avg       0.59      0.53      0.55       293
weighted avg       0.81      0.83      0.81       293

In [9]:
df.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [10]:
new_day = pd.DataFrame([{
    "precipitation": 0.0,
    "temp_max": 16.5,
    "temp_min": 6.0,
    "wind": 3.2
}])

pred = rf.predict(new_day)
print("Tahmin:", le.inverse_transform(pred))

Tahmin: ['sun']